export { HomePage } from './HomePage';
export { HotelDetailPage } from './HotelDetailPage';
export { BookingPage } from './BookingPage';
export { BookingServicesPage } from './BookingServicesPage';
export { PaymentPage } from './PaymentPage';
export { BookingConfirmationPage } from './BookingConfirmationPage';
export { BookingThankYouPage } from './BookingThankYouPage';
export { ProfilePage } from './ProfilePage';
export { ServicesPage } from './ServicesPage';
